#!/bin/bash
python train_.py --env-name KuhnPoker \
  --algo ppo --num-steps 1000 --num-processes 80 --use-gae --eps 1e-8 \
  --lr 2e-4 --entropy-coef 5e-4 --value-loss-coef 0.5 --num-epochs 15 --num-mini-batch 12 --gamma 0.99 --gae-lambda 0.95 \
  --max-grad-norm 2.0 \
  --num-env-steps 5000000 \
  --save-interval 1000000 --log-interval 10000 --eval-interval 100000 --eval-episodes 100 \
  --exp-name "liamx" \
  --wandb-comment "100 episodes of context" \
  --joint-training \
  --hidden-dims 128 128 --act-func relu \
  --recurrent-policy --rnn-hidden-dim 128 --rnn-chunk-length 20 --share-actor-critic \
  --all-has-last-action \
  --collect-peer-traj \
  --auxiliary-peer-obs-pred-coef 1.0 \
  --auxiliary-peer-act-pred-coef 1.0 \
  --train-pool-size 40 --eval-pool-size 10 \
  --rule-based-opponents 40 \
  --use-dummy-vec-env \
  --use-meta-episode \
  --history-size 100 \
  --seed $1 \
  --wandb-user-name <wandb_user_name>
