name: pace
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pillow
  - pyyaml
  - pip:
    - torch==1.12.1
    - torchvision==0.13.1
    - flask==2.3.0
    - flask-socketio==5.3.4
    - python-socketio==5.9.0
    - eventlet==0.33.3
    - pygame==2.1.0
    - scipy
    - opencv-python
    - tqdm
    - wandb
    - gym==0.21.0
    - pettingzoo==1.22.0
    - supersuit
