# Format goes like this
# trainer_name:
#   k: v

name: overcooked
mode: 1to1_env_3_divider
horizon: 40
recipes : [ "LettuceOnionSalad",
            "TomatoCarrotSalad",
            "PotatoBroccoliSalad",
            ]
obs_spaces: dense_partial
obs_range: 8
num_agents: 2
interact_reward: 0.5
progress_reward: 1.0
complete_reward: 10.0
step_cost: 0.2
#display: True
